In [1]:
import numpy as np
import tensorflow as tf
import uncertainty_metrics.tensorflow as umtf
import uncertainty_metrics.numpy as umnp
import tensorflow_probability as tfp

In [2]:
pred_prob = np.array([0.7,0.67,0.23,0.19,0.9,0.97,0.54,0.77,0.15,0.3,0.85,0.69,0.34,0.45,0.53])
# pred_prob = np.array([0.7,0.67,0.77,0.81,0.9,0.97,0.54,0.77,0.85,0.7,0.85,0.69,0.66,0.55,0.53])
# pred_prob = np.array([0.7,0.67,0.82,0.82,0.9,0.97,0.54,0.77,0.75,0.6,0.85,0.69,0.4,0.45,0.53])
# true_class = np.array([1,0,1,2,1,0,1,2,2,0,1,2,0,1,0])

true_class = np.array([1,0,1,0,1,0,0,0,1,0,1,1,0,1,1])

In [3]:
pred_prob_sort = np.sort(pred_prob)
pred_prob_sort

array([0.15, 0.19, 0.23, 0.3 , 0.34, 0.45, 0.53, 0.54, 0.67, 0.69, 0.7 ,
       0.77, 0.85, 0.9 , 0.97])

In [4]:
true_class_sort = np.array([1,0,1,0,0,1,1,0,0,1,1,0,1,1,0])
true_class_sort

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [5]:
from sklearn.isotonic import IsotonicRegression
ir = IsotonicRegression() # create an instance of the IsotonicRegression class
# Fit isotonic regression model
ir.fit(pred_prob, true_class) # fit the model
# y_ir = ir.fit_transform(pred_prob, true_class) # fit the model and transform the data
pred_prob_cl = ir.transform(pred_prob) # transform the data

In [6]:
pred_prob_cl

array([0.66666667, 0.5       , 0.4       , 0.4       , 0.66666667,
       0.66666667, 0.5       , 0.66666667, 0.4       , 0.4       ,
       0.66666667, 0.66666667, 0.4       , 0.5       , 0.5       ])

In [7]:
pred_prob

array([0.7 , 0.67, 0.23, 0.19, 0.9 , 0.97, 0.54, 0.77, 0.15, 0.3 , 0.85,
       0.69, 0.34, 0.45, 0.53])

### Isotonic Regression Optimization:

The goal of isotonic regression is to find a piecewise constant monotonic function that best fits the data points while preserving the order of the original values. The optimization process typically involves the following steps:

Sorting: First, sort the original predicted probabilities in ascending order:

[0.1, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 0.95, 0.98, 0.99]

Initialization: Start with an initial piecewise constant function that is non-decreasing. This function is often initialized as a simple linear function, like taking the average of the first two data points:


[0.2, 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]

Optimization: The optimization process aims to adjust the values of the piecewise constant function to minimize a cost function, such as the mean squared error (MSE) between the ground truth and the calibrated probabilities.

Starting with the initialized function, the algorithm iteratively makes adjustments to the function's values to improve its fit to the data while maintaining monotonicity.
It moves through the data points, identifying regions where the function needs to increase or stay constant to better match the data.
The optimization stops when the function converges to a solution that minimizes the cost function.
Here's how the isotonic function might evolve during optimization in our example:

Initial Function:

[0.2, 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]

After Optimization (simplified for illustration):

[0.15, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 0.9, 0.95, 0.975]

Use in Inference: During inference, when you receive new predicted probabilities from your model, you can apply this calibrated isotonic function to adjust the probabilities before making predictions.